version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asial/Kolkata
  open-pull-requests-limit: 5
  versioning-strategy: increase
